apiVersion: v1
data:
  .dockerconfigjson: "{\"auths\":{\"registry.replicated.com\":{\"username\":{{repl Installation "license_id"}},\"password\":{{repl Installation "license_id"}},\"email\":\"deprecated@example.com\",\"auth\":\"foo\"}}"
kind: Secret
metadata:
  name: auditlog-imagepull-secret
  namespace: auditlog
type: kubernetes.io/dockerconfigjson
