apiVersion: v1
data:
  .dockerconfigjson: {{repl print "{\"auths\": {\"registry.replicated.com\":{\"username\":\"" (Installation "license_id") "\",\"password\":\"" (Installation "license_id") "\" } } } " | Base64Encode }}
kind: Secret
metadata:
  name: auditlog-imagepull-secret
  namespace: auditlog
type: kubernetes.io/dockerconfigjson
